### ISSUE TITLE
Callback doesn't seem to be called

### ISSUE THREAD

**Issue by norro** [jhdcs/rqt_robot_monitor#1]
I ran the rqt_robot_montor on dashing using this command:
`ros2 run rqt_robot_montor rqt_robot_montor`
Then I ran the ROS2 [diagnostic aggregator example from the diagnostics aggregator PR/branch](https://github.com/boschresearch/ros2_diagnostics/blob/ros2_migrate_diagnostic_aggregator/diagnostic_aggregator/example/example.md) using these two commands:
`python3 ./example_pub.py`
`ros2 run diagnostic_aggregator aggregator_node __params:=./example.yaml`
I can see with `ros2 topic info` that rqt_robot_montor subscribes to `/diagnostics_agg`, but no callback is called.

To be sure, I also tested sending blank messages with `ros2 topic pub /diagnostics_agg diagnostic_msgs/DiagnosticArray`, but also no callback called.

Let me know if I can add further dewbug info or test anything else.

**Comment by jhdcs** [comment]
After much searching, we've discovered why the callback isn't being called - the node isn't being spun.

In the original version of the code (i.e: ROS 1), it seems that Python nodes sort-of spun automatically. The `spin()` command just kept the node from closing down, and Python from exiting the program. Since there were other things that were keeping Python from exiting (the GUI, for instance), it appears the original authors omitted the spin() call.

The catch is, now we need to find where in the code we can insert a spin(), and how to keep this spin() from blocking the rest of the code from executing...

**Comment by norro** [comment]
It might be worth to have a look at the [rqt_runtime_monitor (dashing-devel)](https://github.com/ros-visualization/rqt_runtime_monitor/tree/dashing-devel), which seemed to be spun correctly and displayed diagnostic messages in my setup.
However, I can't find an explicit `spin` there either.

**Comment by jhdcs** [comment]
I hooked a `spin_once()` command into the timer callback that checks for messages. I figured that would be the most logical place to put it. Downside is, this means that the subscriber is only going to poll for messages once per second. Not sure if this is going to be an issue.

**Comment by norro** [comment]
The diagnostic aggregator will by default update with 1Hz anyway, so this should not be a pressing issue anymore.

I can see the aggregated diagnostics in the rqt_robot_monitor now! (with the example setup given above). Well done!

**Comment by jhdcs** [comment]
In that case I will close this out. Thanks for triple checking!
